In [1]:
import numpy as np
#Loading the dataset
from sklearn.datasets import load_iris
data = load_iris()

# Print the information contained within the dataset
print("\nKeys of iris_dataset: \n{}".format(data.keys()))
print(data['DESCR'][:500] + "\n...")

#Print the feature names
print("\nFeature names: \n{}".format(data['feature_names']))

#Print the classes
print("\nTarget names: {}".format(data['target_names']))

#Printing the  Few Rows
print("\nFirst five rows of data:\n{}".format(data['data'][:5]))

#Print the class values few datapoints
print("\nTarget:\n{}".format(data['target'][:5]))

#Print the dimensions of data
print("\nShape of data: {}".format(data['data'].shape))


# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set using stratification
tsize=0.25 #test set size to 25% of total examples
X_train, X_test, Y_train, Y_test = train_test_split(data.data, data.target, stratify=data.target,test_size=tsize) 

##### The code for building the model and getting the accuracy #####
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier
#Import scikit-learn metrics module for accuracy calculation

#setting hyperparameters of the KNN Model
metr='euclidean' #other options:{'euclidean','minkowski','manhattan'},etc.
K=1

#Create KNN Classifiers
knn = KNeighborsClassifier(n_neighbors=K,metric=metr);   

#Train the classifier model using the training set
knn.fit(X_train, Y_train)

#Predict the response for test data x_new(dimensions of the new iris flower to be classified)
x_new = np.array([[5, 2.9, 1, .2]])
y_pred = knn.predict(x_new)

print("\nTest Data: {}".format(x_new))
print("Prediction: {}".format(y_pred)) 
print("Predicted target name: {}".format(data['target_names'][y_pred]))

# MODEL EVALUATION: Predict the responses for test dataset and calculate model accuracy
# Model Accuracy: how often is the classifier correct?
Y_pred = knn.predict(X_test)
print("\nTest set predictions:\n {}".format(Y_pred))
print("\nK={}, Distance metric = {} \n%Accuracy on Test set = {:.2f}".format(K,metr,np.mean(Y_pred == Y_test)*100))



Keys of iris_dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                

...

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target names: ['setosa' 'versicolor' 'virginica']

First five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Target:
[0 0 0 0 0]

Shape of data: (150, 4)

Test Data: [[5.  2.9 1.  0.2]]
Prediction: [0]
Predicted t