In [2]:
import numpy as np


In [11]:
s=np.array([1,2,3,4,5])
print(s)

[1 2 3 4 5]


In [8]:
print(type(s))

<class 'numpy.ndarray'>


In [12]:
#dimention of ndarray
s.shape

(5,)

In [20]:
s=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(s)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [18]:
s.shape


(2, 5)

In [22]:
s.T

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [24]:

#dot product
np.dot(s,s.T)

array([[55, 70],
       [70, 90]])

In [27]:
#np.random.randint(starting,ending,No_of_values)
np.random.randint(5,10,15)

array([5, 9, 5, 9, 8, 7, 9, 9, 6, 9, 7, 9, 6, 9, 8])

In [29]:
matrix=np.random.randint(5,10,(3,3))

In [31]:
print(matrix)

[[5 8 5]
 [8 8 5]
 [9 8 7]]


In [33]:
#max element 
np.min(matrix)

5

In [35]:
#min element
np.max(matrix)

9

In [37]:
#index of min element
np.argmin(matrix)

0

In [39]:
#index of max element
np.argmax(matrix)

6

In [42]:
s=np.random.randint(1,10,7)

In [45]:
print(s)

[8 6 8 2 2 5 7]


In [50]:
print(np.unique(s))
print(np.unique(s,return_counts=True))


[2 5 6 7 8]
(array([2, 5, 6, 7, 8]), array([2, 1, 1, 1, 2], dtype=int64))


In [52]:
matrix

array([[5, 8, 5],
       [8, 8, 5],
       [9, 8, 7]])

In [54]:
#slicing of matrix matrix[row:row2,col:col2]
print(matrix[0:1,1:2])

[[8]]


In [55]:
print(matrix[0:2,1:2])

[[8]
 [8]]
